version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    directory: /apps/app
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      expo-sdk:
        patterns:
          - "@expo/*"
          - "expo*"
          - "react-native*"

  - package-ecosystem: pip
    directory: /runner
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
