import type { Href } from "expo-router";

/**
 * The typed-routes snapshot in `.expo/types` is generated by `expo start` /
 * `expo export` and lags behind newly added screens, so the More-tab routes
 * are widened here and validated by expo-router at runtime. Replace with
 * typed hrefs once the snapshot includes them.
 */
export function toHref(path: string): Href {
  return path as Href;
}
