import { spawn } from "node:child_process";
import { webcrypto } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ulid } from "ulid";

const PBKDF2_ITERATIONS = 100_000;
const DEMO_EMAIL = "demo@zenguy.dev";
const DEMO_PASSWORD = "Password123!";
const SCRIPT_DIRECTORY = path.dirname(fileURLToPath(import.meta.url));
const API_DIRECTORY = path.resolve(SCRIPT_DIRECTORY, "..");
const GENERATED_SQL_PATH = path.join(SCRIPT_DIRECTORY, ".seed.generated.sql");
const encoder = new TextEncoder();

function parseArguments(argv) {
  const options = {
    dryRun: false,
    remote: false,
    allowRemote: false,
    varsFile: path.join(API_DIRECTORY, ".dev.vars"),
  };
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === "--") continue;
    if (argument === "--dry-run") options.dryRun = true;
    else if (argument === "--remote") options.remote = true;
    else if (argument === "--allow-remote") options.allowRemote = true;
    else if (argument === "--vars-file") {
      const value = argv[index + 1];
      if (value === undefined || value.startsWith("--")) {
        throw new Error("--vars-file requires a path");
      }
      options.varsFile = path.resolve(process.cwd(), value);
      index += 1;
    } else {
      throw new Error(`Unknown argument: ${argument}`);
    }
  }
  if (options.remote && !options.allowRemote) {
    throw new Error(
      "Refusing to seed remote D1 without the explicit --allow-remote flag",
    );
  }
  return options;
}

function parseVars(contents) {
  const values = new Map();
  for (const sourceLine of contents.split(/\r?\n/u)) {
    const line = sourceLine.trim();
    if (line === "" || line.startsWith("#")) continue;
    const separator = line.indexOf("=");
    if (separator <= 0) continue;
    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'")))
    ) {
      value = value.slice(1, -1);
    }
    values.set(key, value);
  }
  return values;
}

function randomBytes(length) {
  return webcrypto.getRandomValues(new Uint8Array(length));
}

function base64(bytes) {
  return Buffer.from(bytes).toString("base64");
}

function exactBuffer(bytes) {
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
}

async function hashPassword(password) {
  const salt = randomBytes(16);
  const material = await webcrypto.subtle.importKey(
    "raw",
    encoder.encode(password),
    "PBKDF2",
    false,
    ["deriveBits"],
  );
  const bits = await webcrypto.subtle.deriveBits(
    {
      name: "PBKDF2",
      hash: "SHA-256",
      salt: exactBuffer(salt),
      iterations: PBKDF2_ITERATIONS,
    },
    material,
    256,
  );
  return `pbkdf2$${PBKDF2_ITERATIONS}$${base64(salt)}$${base64(
    new Uint8Array(bits),
  )}`;
}

async function encryptSecret(plaintext, encryptionKey) {
  const iv = randomBytes(12);
  const key = await webcrypto.subtle.importKey(
    "raw",
    exactBuffer(encryptionKey),
    { name: "AES-GCM" },
    false,
    ["encrypt"],
  );
  const ciphertext = await webcrypto.subtle.encrypt(
    { name: "AES-GCM", iv: exactBuffer(iv) },
    key,
    encoder.encode(plaintext),
  );
  return `v1:${base64(iv)}:${base64(new Uint8Array(ciphertext))}`;
}

function sqlString(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

function seedId(at, offset) {
  return `seed_${ulid(at + offset)}`;
}

async function generateSql(encryptionKey) {
  const now = Date.now();
  const periodEnd = now + 30 * 24 * 60 * 60 * 1_000;
  const ids = {
    user: seedId(now, 0),
    workspace: seedId(now, 1),
    member: seedId(now, 2),
    subscription: seedId(now, 3),
    secret: seedId(now, 4),
    channel: seedId(now, 5),
    browserTest: seedId(now, 6),
    monitor: seedId(now, 7),
  };
  const [passwordHash, encryptedSecret, encryptedChannel] = await Promise.all([
    hashPassword(DEMO_PASSWORD),
    encryptSecret("demo-secret-value", encryptionKey),
    encryptSecret(JSON.stringify({ emails: [DEMO_EMAIL] }), encryptionKey),
  ]);
  const statements = [
    "-- Generated by scripts/seed.mjs. Do not edit or commit.",
    `-- Generated at ${new Date(now).toISOString()}.`,
    "",
    "DELETE FROM uptime_checks WHERE id LIKE 'seed_%';",
    "DELETE FROM uptime_monitor_channels WHERE uptime_monitor_id LIKE 'seed_%';",
    "DELETE FROM uptime_monitors WHERE id LIKE 'seed_%';",
    "DELETE FROM run_artifacts WHERE id LIKE 'seed_%';",
    "DELETE FROM run_steps WHERE id LIKE 'seed_%';",
    "DELETE FROM test_attempts WHERE id LIKE 'seed_%';",
    "DELETE FROM test_runs WHERE id LIKE 'seed_%';",
    "DELETE FROM browser_test_channels WHERE browser_test_id LIKE 'seed_%';",
    "DELETE FROM browser_tests WHERE id LIKE 'seed_%';",
    "DELETE FROM notification_deliveries WHERE id LIKE 'seed_%';",
    "DELETE FROM incident_events WHERE id LIKE 'seed_%';",
    "DELETE FROM incidents WHERE id LIKE 'seed_%';",
    "DELETE FROM notification_channels WHERE id LIKE 'seed_%';",
    "DELETE FROM workspace_secrets WHERE id LIKE 'seed_%';",
    "DELETE FROM overage_reports WHERE id LIKE 'seed_%';",
    "DELETE FROM usage_events WHERE id LIKE 'seed_%';",
    "DELETE FROM subscriptions WHERE id LIKE 'seed_%';",
    "DELETE FROM audit_logs WHERE id LIKE 'seed_%';",
    "DELETE FROM workspace_invitations WHERE id LIKE 'seed_%';",
    "DELETE FROM workspace_members WHERE id LIKE 'seed_%';",
    "DELETE FROM workspaces WHERE id LIKE 'seed_%';",
    "DELETE FROM refresh_tokens WHERE id LIKE 'seed_%';",
    "DELETE FROM email_tokens WHERE id LIKE 'seed_%';",
    "DELETE FROM users WHERE id LIKE 'seed_%';",
    `DELETE FROM users WHERE email = ${sqlString(DEMO_EMAIL)};`,
    "",
    `INSERT INTO users (id, name, email, password_hash, email_verified_at, created_at, updated_at) VALUES (${sqlString(ids.user)}, 'Demo User', ${sqlString(DEMO_EMAIL)}, ${sqlString(passwordHash)}, ${now}, ${now}, ${now});`,
    `INSERT INTO workspaces (id, name, slug, timezone, owner_user_id, created_at, updated_at, deleted_at) VALUES (${sqlString(ids.workspace)}, 'Demo Workspace', 'demo-workspace', 'Europe/Madrid', ${sqlString(ids.user)}, ${now}, ${now}, NULL);`,
    `INSERT INTO workspace_members (id, workspace_id, user_id, role, invited_by, joined_at) VALUES (${sqlString(ids.member)}, ${sqlString(ids.workspace)}, ${sqlString(ids.user)}, 'OWNER', NULL, ${now});`,
    `INSERT INTO subscriptions (id, workspace_id, provider, provider_customer_id, provider_subscription_id, status, period_start, period_end, cancel_at_period_end, update_payment_url, cancel_url, created_at, updated_at) VALUES (${sqlString(ids.subscription)}, ${sqlString(ids.workspace)}, 'paddle', 'seed-local', 'seed-local', 'ACTIVE', ${now}, ${periodEnd}, 0, NULL, NULL, ${now}, ${now});`,
    `INSERT INTO workspace_secrets (id, workspace_id, key, encrypted_value, encryption_version, allowed_domains, description, created_by, created_at, updated_at) VALUES (${sqlString(ids.secret)}, ${sqlString(ids.workspace)}, 'DEMO_TOKEN', ${sqlString(encryptedSecret)}, 1, '["*.example.com"]', 'Demo token', ${sqlString(ids.user)}, ${now}, ${now});`,
    `INSERT INTO notification_channels (id, workspace_id, name, type, encrypted_config, enabled, verified_at, last_delivery_status, created_by, created_at, updated_at) VALUES (${sqlString(ids.channel)}, ${sqlString(ids.workspace)}, 'Demo email', 'EMAIL', ${sqlString(encryptedChannel)}, 1, NULL, NULL, ${sqlString(ids.user)}, ${now}, ${now});`,
    `INSERT INTO browser_tests (id, workspace_id, name, start_url, instructions, device, interval_hours, max_retries, notify_on_recovery, next_run_at, created_by, updated_by, created_at, updated_at, deleted_at) VALUES (${sqlString(ids.browserTest)}, ${sqlString(ids.workspace)}, 'Example smoke', 'https://example.com', 'Check that the page shows the heading ''Example Domain'' and contains a link labeled ''More information''.', 'DESKTOP', 24, 1, 1, ${now + 24 * 60 * 60 * 1_000}, ${sqlString(ids.user)}, ${sqlString(ids.user)}, ${now}, ${now}, NULL);`,
    `INSERT INTO browser_test_channels (browser_test_id, notification_channel_id) VALUES (${sqlString(ids.browserTest)}, ${sqlString(ids.channel)});`,
    `INSERT INTO uptime_monitors (id, workspace_id, name, url, method, encrypted_headers, encrypted_body, expected_status, body_condition, body_expected_value, body_condition_path, frequency_seconds, timeout_seconds, max_retries, notify_on_recovery, next_check_at, current_status, current_cycle_id, cycle_started_at, last_check_at, last_response_time_ms, created_by, created_at, updated_at, deleted_at) VALUES (${sqlString(ids.monitor)}, ${sqlString(ids.workspace)}, 'Example uptime', 'https://example.com', 'GET', NULL, NULL, 200, NULL, NULL, NULL, 300, 10, 1, 1, ${now + 300_000}, 'UNKNOWN', NULL, NULL, NULL, NULL, ${sqlString(ids.user)}, ${now}, ${now}, NULL);`,
    `INSERT INTO uptime_monitor_channels (uptime_monitor_id, notification_channel_id) VALUES (${sqlString(ids.monitor)}, ${sqlString(ids.channel)});`,
    "",
  ];
  return statements.join("\n");
}

async function executeSql(remote) {
  const arguments_ = [
    "wrangler",
    "d1",
    "execute",
    "zenguy-db",
    remote ? "--remote" : "--local",
    "--file",
    "scripts/.seed.generated.sql",
  ];
  await new Promise((resolve, reject) => {
    const child = spawn("npx", arguments_, {
      cwd: API_DIRECTORY,
      stdio: "inherit",
      shell: process.platform === "win32",
    });
    child.once("error", reject);
    child.once("exit", (code, signal) => {
      if (code === 0) resolve();
      else {
        reject(
          new Error(
            signal === null
              ? `Wrangler exited with code ${String(code)}`
              : `Wrangler was terminated by ${signal}`,
          ),
        );
      }
    });
  });
}

async function main() {
  const options = parseArguments(process.argv.slice(2));
  let varsContents;
  try {
    varsContents = await readFile(options.varsFile, "utf8");
  } catch (error) {
    throw new Error(
      `Cannot read ${options.varsFile}; create apps/api/.dev.vars first`,
      { cause: error },
    );
  }
  const encryptionKeyValue = parseVars(varsContents).get("ENCRYPTION_KEY");
  if (encryptionKeyValue === undefined || encryptionKeyValue === "") {
    throw new Error(`ENCRYPTION_KEY is missing from ${options.varsFile}`);
  }
  const encryptionKey = new Uint8Array(
    Buffer.from(encryptionKeyValue, "base64"),
  );
  if (encryptionKey.byteLength !== 32) {
    throw new Error("ENCRYPTION_KEY must decode to exactly 32 bytes");
  }
  const sql = await generateSql(encryptionKey);
  if (options.dryRun) {
    process.stdout.write(sql);
    return;
  }
  await writeFile(GENERATED_SQL_PATH, sql, "utf8");
  await executeSql(options.remote);
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`Seed failed: ${message}\n`);
  process.exitCode = 1;
});
